version: '3.8'

services:
  acestream-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acestream-scraper-arm64
    environment:
      - TZ=Europe/Madrid
      - ENABLE_TOR=false
      - ENABLE_ACEXY=true
      - ENABLE_ACESTREAM_ENGINE=true
      - ACESTREAM_HTTP_PORT=6878
      - FLASK_PORT=8000
      - ACEXY_LISTEN_ADDR=:8080
      - ACEXY_HOST=localhost
      - ACEXY_PORT=6878
      - ALLOW_REMOTE_ACCESS=no
      - ACEXY_NO_RESPONSE_TIMEOUT=15s
      - ACEXY_BUFFER_SIZE=5MiB
      - ACESTREAM_HTTP_HOST=ACEXY_HOST
      - ENABLE_WARP=true
      - WARP_ENABLE_NAT=true
      - WARP_ENABLE_IPV6=false
      - IPV6_DISABLED=true
    ports:
      - "8000:8000"  # Flask application
      - "8080:8080"  # Acexy proxy
      - "8621:8621"  # Acestream P2P Port
      - "43110:43110"  # ZeroNet UI
      - "43111:43111"  # ZeroNet peer
      - "26552:26552"  # ZeroNet peer
    volumes:
      - ./data/zeronet:/app/ZeroNet/data
      - ./data/config:/app/config
    # Capacidades necesarias para WARP
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    # Acceso al dispositivo TUN para WARP
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped